version: '3.1'
name: "GOTASKAPP"
services:
  database:
    image: 'mariadb:10'
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - 'database:/var/lib/mysql'
volumes:
  database:
    driver: local